### ISSUE TITLE
Remarque user

### ISSUE THREAD

**Issue by nicolas-eoxia** [Evarisk/DoliSMQ#1521]
**IHM**
- [ ] Picto apte/inapte confusion avec picto validé
**Utilisation Phone**
1. [x] Accès a la page #1523 
2. [ ] [Tableau non responsive participant](https://github.com/Evarisk/Saturne/issues/637) 
3. [ ] Signature, confusion avec le bouton document 
4. [ ] Amélioration du bouton Save #1525
5. [ ] Besoin d'un auto-save sur les questions
6. [ ] Picto unlock confusion
7. [ ] Message confirm pas vraiment lu
8. [ ] Info que le contrôle a été signé par la personne souhaite (module notification)

**Comment by lmag** [comment]
Picto unlock confusion
Devient 1 seul bouton " Valider" et "Dé-valider"
Téléchargement du document à signer

![image](https://github.com/Evarisk/DoliSMQ/assets/3288514/c8f9a219-8881-4c9d-8821-bff80b121aa1)

à refaire
![image](https://github.com/Evarisk/DoliSMQ/assets/3288514/213e039c-cfc6-4abd-ac08-c035e7b8da06)
