### ISSUE TITLE
import checklist

### ISSUE THREAD

**Issue by evarisk-micka** [Evarisk/DoliSMQ#764]
de37316f05147781dfeb0fc24513a58bcb0d2671

Importer les fiches modèles et créer des objets pour chaque questions + fiche modèle

// Nouvelle nouvelle demande

- [x]  Recréer l'outil d'import/export comme sur Digirisk
- [x]  Ajouter l'export des données en JSON
- [x]  Ajouter l'import des données en JSON

Ajouter les droits sheet sur la page dans le mod
Retirer la partie export en dessous
Importer un fichier zip et pas json
date->create = now
Remplacer "exportation/importation" par "export/import" et enlever "vers un fichier", "vers Dolibarr" dans le titre
modèleS
mettre photo->ok/ko à vide

d7b7f109be632392f2fef78c23099f89576ab9a9

// Nouvelle demande
- [x] Import / export des questions et fiches modèles
- [x] Pour chaque fiche modèle, export chacune de ses questions et pour chaque question ses réponses
- [x] Pareil mais pour l'import

// Ancienne demande
- [x] Créer onglet outils
- [x] Importer fichier
- [x] Trier data en fonction d'un format
- [x] Possibilité d'importer .txt

nouveau : 
changer exportation par export et importation par import, partout
changer JSON par zip dans les trad vu qu'on dl un zip
Fiche modèle plutot que Fiche sur la page export
les deux exports donnent le meme ficher (en tout cas ils ont le meme nom)
warning a l'import de ficher
import question /answer ne marche pas sur une nouvelle entité, l'autre fonctionne bien
seteventmessage verbose 
trad exportdata

1209ca44c825b4d774ade3bd5aca71fa007526ff

Migration des ... =>
Export des données de DoliSMQ
Import des données vers DoliSMQ
Langsload exportdata
bdf5ea5919801bf179347817fef266c936fbb0a8

- [x] double check require dolismq main sur tools
- [x] enlever dolismq tools lib
- [x] exporter mes données trad à mettre dans saturne
- [x] aligner traductions
- [x] enlever padding menu tools
- [x] enlever commentaire avec DoliSMQ
- [x] export + import aplatir les foreach
- [x] count() plutot que count++
- [x] pas besoin de créer les ref sheet/questions/réponses c'est automatique dans la classe
- [x] date_creation pas forcément utile ca doit se faire dans la classe
- [x] status a set avec la valeur du tableau et dans la classe pas override status s'il est set
- [ ] 

8b1b8060cf32c2fc49943396b99bc07eca847cd0

- [x] this->status = (this->status ?: 1);
- [x] lors des getpost et instanciation objet, séparer comme le standard
- [x] Mettre les action et getpost en snake_case
- [x] Rajouter un 0 au dernier paramètre de fetchQuestionsLinked
- [x] Préinstancier dolismqexportarray et appeler le dernier dolismqexportjson
- [x] fileDir et fileName et fileNameZip
- [x] Vérifier alignement
- [x] count = sheetCounter
- [x] count = questionCounter
- [x] virer export de date_creation, date_modif, photo okko
- [x] datamigrationimportjson => datamigrationimportzip
ee103dbd561e06a7976841859f28f1310ac44f62
3600b053b58480e90c7bf8f663cd1af1fa367596

**Comment by evarisk-micka** [comment]
Regarder le script d'export natif et d'import
Passer par l'outil d'export si solution envisageable

Export CSV : 
-Question (répéter la ref de la questions pour x réponses dessus)
-Fiche modèle (répéter la ref de la fiche modèle pour x questions dessus)
